#!/usr/bin/env node
/**
 * Credits builder.
 *
 * Walks src/collection/, groups every design by its declared artist, and writes AUTHORS.md.
 * Attribution is a licence condition, not a courtesy — this file is generated so that the
 * credit roster can never drift from the metadata that governs it.
 *
 * Run from the repository root:  node scripts/build-authors.mjs
 */

import { readdirSync, readFileSync, writeFileSync, statSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

/** Anchor every path to the repository root so the script runs from any directory. */
const REPO_ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const fromRoot = (...segments) => join(REPO_ROOT, ...segments);

const COLLECTION_DIR = 'src/collection';
const OUTPUT = 'AUTHORS.md';

const TIER_BY_FOLDER = {
  'hero-patterns': 'hero',
  'secondary-patterns': 'secondary',
  'blender-patterns': 'blender',
};

/** artist display name -> { github, url, country, collective, assets[] } */
const artists = new Map();

for (const [folder, tier] of Object.entries(TIER_BY_FOLDER)) {
  const tierPath = fromRoot(COLLECTION_DIR, folder);
  if (!existsSync(tierPath)) continue;

  for (const design of readdirSync(tierPath).sort()) {
    const designPath = join(tierPath, design);
    if (!statSync(designPath).isDirectory()) continue;

    const metaPath = join(designPath, 'meta.json');
    if (!existsSync(metaPath)) continue;

    const meta = JSON.parse(readFileSync(metaPath, 'utf8'));
    const author = meta.author ?? {};
    const name = author.display_name;

    if (!name) {
      console.error(`✖ ${COLLECTION_DIR}/${folder}/${design}: meta.json has no author.display_name.`);
      console.error('  Attribution is mandatory. See LICENSE-ASSETS.md → "How to credit".');
      process.exit(1);
    }

    if (!artists.has(name)) {
      artists.set(name, {
        github: author.github ?? null,
        url: author.url ?? null,
        country: author.country ?? null,
        collective: author.collective ?? null,
        assets: [],
      });
    }

    artists.get(name).assets.push({
      id: meta.id,
      version: meta.version ?? 'v01',
      tier,
      title: meta.title?.en ?? meta.id,
    });
  }
}

const sorted = [...artists.entries()].sort(([a], [b]) => a.localeCompare(b));
const assetCount = sorted.reduce((total, [, artist]) => total + artist.assets.length, 0);

const lines = [
  '<!-- Generated by scripts/build-authors.mjs. Do not edit by hand. -->',
  '<!-- Run `npm run build:authors` after adding or changing an asset. -->',
  '',
  '# Authors',
  '',
  'Every surface design in this archive is the work of a named artist who **retains their copyright**',
  'and licenses the work under [CC BY-SA 4.0](LICENSE-ASSETS.md). Anyone using these designs — including',
  'commercially — must credit the individual artist listed here, not this repository alone.',
  '',
  'See [LICENSE-ASSETS.md → How to credit](LICENSE-ASSETS.md#how-to-credit--required-attribution-format)',
  'for the required attribution formats.',
  '',
  `**${sorted.length} artist(s) · ${assetCount} design(s).**`,
  '',
];

if (sorted.length === 0) {
  lines.push(
    '_No artwork has been contributed yet. The first merged design will appear here automatically._',
    '',
    'To be listed, see [CONTRIBUTING.md → Artistic contribution path](CONTRIBUTING.md#artistic-contribution-path).',
    '',
  );
} else {
  for (const [name, artist] of sorted) {
    const handle = artist.github ? ` — [${artist.github}](https://github.com/${artist.github.slice(1)})` : '';
    const site = artist.url ? ` · [portfolio](${artist.url})` : '';
    lines.push(`## ${name}${handle}${site}`, '');
    if (artist.collective) lines.push(`In collaboration with **${artist.collective}**.`, '');
    for (const asset of artist.assets.sort((a, b) => a.id.localeCompare(b.id))) {
      lines.push(`- **${asset.title}** — \`${asset.id}-${asset.version}\` (${asset.tier})`);
    }
    lines.push('');
  }
}

lines.push(
  '## Translators and maintainers',
  '',
  'Locale maintainers and core maintainers are listed in [MAINTAINERS.md](MAINTAINERS.md). Every',
  'contributor to a release is credited by name in [CHANGELOG.md](CHANGELOG.md).',
  '',
);

writeFileSync(fromRoot(OUTPUT), `${lines.join('\n')}`);
console.log(`✔ Wrote ${OUTPUT} — ${sorted.length} artist(s), ${assetCount} design(s).`);
